server:
  port: 8080

spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?useSSL=false
    username: root
    password: yzx123456
#freemarker模板配置
  freemarker:
    suffix: .ftl
    cache: false
    charset: UTF-8
    contentType: text/html
    requestContextAttribute: ctx
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    settings:
      defaultEncoding: UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
  activiti:
        check-process-definitions: false
        db-identity-used: true
        # 自动生成Activiti相关表 第一次生成后建议关闭提高运行速度
        database-schema-update: true
        # 保存历史数据级别设置为full最高级别，便于历史数据的追溯
        history-level: full
jasypt:
  encryptor:
    password: 123456
